# Generated by Django 3.0.5 on 2020-05-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0002_auto_20200503_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bridge',
            name='year_built',
            field=models.CharField(default='this bridge has no information on year built', max_length=600),
        ),
    ]
