# Generated by Django 3.0.5 on 2020-05-09 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0002_bridge_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bridge',
            name='year_built',
            field=models.CharField(default='unknown year', max_length=600),
        ),
    ]
