# Generated by Django 3.0.5 on 2020-05-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0003_auto_20200508_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bridge',
            name='picture',
            field=models.CharField(default='{% static bridge/default_bridge.jpg %}', max_length=600),
        ),
    ]
