# Generated by Django 3.0.5 on 2020-05-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0004_auto_20200512_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bridge',
            name='picture',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
