# Generated by Django 3.0.5 on 2020-05-19 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0005_auto_20200512_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='bridge',
            name='lat',
            field=models.FloatField(default=-32.6536),
        ),
        migrations.AddField(
            model_name='bridge',
            name='long',
            field=models.FloatField(default=-70.0115),
        ),
    ]
